### PR TITLE
Better logged user handling

### LINKED ISSUE #5: It causes session id to be different for every request
I have a problem with this extension. It causes that I can't login to my web app. I was trying to figure it out, I discovered, that session id is different for every request, this extension somehow causes it, so the session is being forgotten after every request. When I comment out this extension in neon file, everything works as usual.
There are no PHP errors in any log folder. I use the latest stable Nette and PHP 7.4.
I don't know how to describe this problem more. I will try to explore your code and will get back at you if I discover something.
Otherwise it works, it sends messages to our Sentry.
But only causes described session mess.
Can you help me somehow? Can I provide more info?

### PR DESCRIPTION
**Pull request by martenb**
We have same issues, that is described in issue #5 , so i prepared PR, which fixes it.

### CODE REVIEW

**Comment by rootpd** [comment]
@martenb  Thanks a lot for the PR. I'm having a bit harder time understanding what was the cause of the issue. Could you please describe the change? It looks the same to me, but I must be missing something.

This is how I read it:

- The actual `log()` logging is only executed if identity is not null. Previously it was handled by `if ($this->identity)` condition.
- Identity is available for access only if user is set and logged in. Previously it was handled by `if ($user->isLoggedIn())` in `setUser` method.
- User is not used in any new way.

Thanks.

**Comment by martenb** [comment]
Main problem is, that User::getIdentity() was called in beforeCompile, so if you have changed UserStorage::setNamespace() in Presenter, described in the issue, it causes that you were unable to login to app.
So only thing i have changed is, that User::getIdentity() is called after error ocurs, not in beforeComplie..

**Comment by martenb** [comment]
```php
// if you do this in BasePresenter, you are unable to login
// not sure, why
$this->getUser()->getStorage()->setNamespace('Admin');
```

Now this works and correct user is logged to sentry (with corrent namespace).

**Comment by rootpd** [comment]
Wow, thanks a lot.

**Pull request merged**
